My capstone project
dami1080/Capstone-conference-project pull request #1
Opened 2021-07-01 14:35 UTC by dami1080

In this pull request, I  have; 

- added an HTML file
- added a CSS file
- all linters are now passing
- added readme file
- an app.js file

           **The following was implemented**

- Create a javascript array of objects to store speakers
 - Populate the speakers dynamically on page load
- Add media queries for screens below 768px below and 768px and above
- The home page has a link in the menu to the about page.
- The logo in the header links to the home page.
- When the hamburger button on the header is clicked, the mobile menu appears over the page.
- The mobile menu has a close (X) button that closes the menu.

2021-07-01 17:18 UTC, de-scholar requested changes
Hi @dami1080 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._
- [ ] The video should contains a clear and objective description about the project in professional English. The topic and purpose of the project are made clear.
- [ ] The video should contain a highlight about a piece of the code the student finds interesting or is proud of making.

:point_right: I suggest you record another video which fulfill all of the video presentation requirements! 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-01 17:18 UTC, de-scholar commented on about.html
> +</html>
- [ ] There should be at least 1, but no more than 1, h1 tag in each page.

2021-07-01 17:18 UTC, de-scholar commented on index.html
> +</html>
- [ ] There's at least 1, but no more than 1, h1 tag in each page.
- [ ] The page is accessible, images contain alt attributes and there's not images or elements blocking the text in both screen sizes.

2021-07-01 20:22 UTC, ElijahTobs requested changes
# Status: Changes Required ⚠️ 🚦
## Hi @dami1080  👋

You've done really well so far! 👍 

## Major Highlights 💯 

Your README is professional ✔️ 
You've followed the Github flow rules. ✔️ 
You have good commit messages ✔️ 
Nice Pull Request description ✔️ 
Linter checks are passing ✔️ 

_However, there are some changes that you are required to make before this project can be approved._

## Required Changes ♻️

_See the inline comments below_

## Optional Changes 👌
_Every comment with the OPTIONAL prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend that you take them into account as they can make your code better._

__N/A__

_If anything doesn't seem clear to you, feel free to leave your question or comment in the PR thread below_

#### "Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise."

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
## Happy Coding :computer: 

_Reviewed by_  **Elijah O. Ayandokun**

2021-07-01 20:22 UTC, ElijahTobs commented on about.html
> +                    </p>
- [ ] As the previous reviewer stated, there should be one but not more than one `h1` tag on each page. The `about.html` page currently does not have an `h1` tag

2021-07-01 20:22 UTC, ElijahTobs commented on about.html
> +                            <img src="./images/conference_one.jpg" alt="">
- [ ] The previous reviewer also mentioned the alt attribute but it has not been addressed. The alt tag describes the image or at least states what the image is trying to convey to the person seeing the page. In addition, users of screen magnification may not be able to get a complete view of the image and thus need the alt tag to let them know what the purpose of the image is. The same goes for `line 98`

2021-07-02 09:03 UTC, ElijahTobs approved these changes
# STATUS: APPROVED 🎉 🥇 
## Hi @dami1080 , 

Good job making the required changes.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


_If anything doesn't seem clear to you, feel free to leave your question or comment in the PR thread below_

#### "Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise."

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

_Reviewed by_: __**Elijah Ayandokun**__

2021-07-02 09:08 UTC, merged